name: DomIRC
url: https://domirc.github.io/
description: A network for domain name owners and communities.

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
